version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: enadif
      MONGO_INITDB_ROOT_PASSWORD: enadif
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: enadif
      ME_CONFIG_MONGODB_ADMINPASSWORD: enadif
      ME_CONFIG_MONGODB_URL: mongodb://enadif:enadif@mongo:27017/
      ME_CONFIG_BASICAUTH: false
